### ISSUE TITLE
[REQ] Relative Paths for Multi Scrapbook

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#110]
I use firefox portable. I use Multi-Scrapbook.
I keep "firefox portable folder" and the "Multi-Scrapbook database folder" in a same folder together.

Now if I move around the master folder (containing both) I have to open scrapbook and manually edit paths of each and every scrapbook I have. It is very tedious.

I would be helpful if I could give relative path to the scrapbook database instead of absolute.

Questions:
What is the maximum limit to the number of scrapbooks in multi-scrapbook?
Is there any way I can donate to you?

**Comment by danny0838** [comment]
This will flush files to the Firefox setting directory and has a security concern. We won't do it in this way.

**Comment by jdunn0** [comment]
@grotesque: I'm curious, why do you need multiple ScrapBooks on a Portable Drive and how often do you move the folder they are in?
I can't imagine you would be moving the folder much at all though I could see the Drive Letter changing on different computers for the Portable Drive.

**Comment by danny0838** [comment]
As a compromise, we'll add an error-proof so that an incomplete path for the scrapbook directory. As a result, the user will be able to specify a relative path by modifying the user preference or the multibook.txt, but the GUI might not recognize them well and could break sometimes. We will not do additional fix for it as it is not an encouraged usage.
