### ISSUE TITLE
Option to remove Scrapbook Manage... icon

### ISSUE THREAD

**Issue by comonp** [danny0838/firefox-scrapbook#119]
Can there be an option to remove the Scrapbook Manage... icon in the Scrapbook sidebar?

![](https://raw.githubusercontent.com/wiki/danny0838/firefox-scrapbook/images/screenshots/029.png)

**Comment by pascallothar** [comment]
Sidebar -> Tools -> Preferences -> General (I translate from French)

or

From Menu bar
Tools -> Add-ons -> Extensions -> ScrapBook X -> Preferences

**Comment by danny0838** [comment]
We will not implement this since there could be thousands of different requests for removing a button, to add a button, or so on. **User style** is a better way to go for those who want such feature. For example, you can install [Stylish](https://userstyles.org/) (or other similar addon), and create a new user script with something like this:

	#ScrapBookWindow #sbToolbarManage {
	  display: none;
	}

**Comment by danny0838** [comment]
After some consideration we decided to remove this button totally since it's really used. We'll apply it in the next release. Thank you for the feedback.
