### ISSUE TITLE
url in link replaced with '#'

### ISSUE THREAD

**Issue by aling** [danny0838/firefox-scrapbook#130]
First I'd like to thank you for taking up the maintenance of this marvelous and indispensable add-on.

Now the bug: Occasionally in the scraped page, the URL in a link is replace by a singe "#". But this almost always happens when the link is added by 'Attach Link to Selection...' during 'Edit Before Capture'.

**Comment by danny0838** [comment]
Which link do you mention when you say 'the URL in a link is replace by a singe "#"'?

**Comment by aling** [comment]
For example, if I:

1. go to the page https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
2. select the title "List of HTTP status codes"
3. click "Attach Link to Selection..." and add the page URL to the selection
4. save the page

I would expect the saved page to contain a link element like this:

`<a href="https://en.wikipedia.org/wiki/List_of_HTTP_status_codes">List of HTTP status codes</a>`

But I get this instead:

`<a href="#">List of HTTP status codes</a>`

I guess I should have worded it more precisely: "the URL in the link element's href attribute is replaced by a single #".

**Comment by aling** [comment]
I just found out that saving any Slashdot page (e.g. https://hardware.slashdot.org/story/16/08/13/201207/will-new-battery-technologies-smash-the-old-order) will replace the title link with a '#'.

By the way, I'm using Firefox 48 on OS X El Capitan.

**Comment by danny0838** [comment]
This is not an issue of ScrapBook X because the content of those links are actually "#", and the page you are redirected to when you click those links in the original page is handled by javascript.

To make the captured page has same link effect you can try capturing scripts, this might work for certain cases. If it still doesn't work then it's something ScrapBook X cannot help. Since javascript veries a lot and could be highly context depended, it's impossible to development a non-ad-hoc solution to make the captured script work in a different context.

**Comment by danny0838** [comment]
For the [3F case](https://github.com/danny0838/firefox-scrapbook/issues/130#issuecomment-239786805) it's also a normal feature since ScrapBook X resolves every link to the page itself into a hash link so that it correctly points to the captured page instead of the original page.

If you really want to link to the original page, capture it, open the captured page, and add the link, so that there is no capture nor a link resolution.

**Comment by aling** [comment]
Thanks for the quick response and explanation.

But I think what you are saying about [4F case](https://github.com/danny0838/firefox-scrapbook/issues/130#issuecomment-239786805) is not true, for I use NoScript plugin to turn off all JavaScript, and I can see the link in the source of original page: `<a href="//hardware.slashdot.org/story/16/08/13/201207/will-new-battery-technologies-smash-the-old-order" title="Back to Article - Will New Battery Technologies Smash The Old Order?">Will New Battery Technologies Smash The Old Order?</a>`. However, what you are saying about converting all self-referencing links to '#' will explain the behavior.

So I guess for both cases, regardless of whether JavaScript is involved, ScrapBook X will convert all self-referencing links into a link to '#'. This must be an implementation change from original ScrapBook and ScrapBook Plus, because they used to work. But I can see some advantages with the new implementation. So I concur this is not a bug but a feature, and the minor inconvenience is acceptable...

Keep up the good work!

**Comment by danny0838** [comment]
The site has a fallback mechanism: for browsers with javascript support, rewrite the href to "#" and use dynamic link; for those with no support, use the original static link.

This would be a good news for you, if you want the links to work right, just disable javascript and catch.
