### ISSUE TITLE
Organize tab is missing in 1.13.0

### ISSUE THREAD

**Issue by mrdc** [danny0838/firefox-scrapbook#140]
Hello,

Organize tab is missing in 1.13.0, so it's not possible to chose a save location.

**Comment by jdunn0** [comment]
The organize tab is still in ScrapBook, what is gone is the "Location to Store Data" section of it as shown here:
![scrapbook-organize-storelocation](https://cloud.githubusercontent.com/assets/9695075/18220617/bc2a9926-7128-11e6-8d5c-0f263e28a923.png)
One feature that can be turned on via that section is "Enable Multi-ScrapBook".
The "Multi-ScrapBook" feature lets you have multiple ScrapBook locations that you can switch between.
Because you can just have one or two entries in Multi-ScrapBook mode, it was decided to just always have Multi-ScrapBook mode turned on and remove support setting the location of just one ScrapBook.

That means to specify where to store ScrapBook data, you need to click the "Multi-ScrapBook" icon on the Scrapbook X sidebar and select "Manage...".
Seeing as how this is not an obvious thing for people not familiar with the "Multi-ScrapBook" feature, I think it would be good idea if a button was added to the Organize tab to open the "Multi-ScrapBook Manager".

**Comment by danny0838** [comment]
@mrdc As @jdunn0 have said, the support for single custom ScrapBook directory has removed in SBX 1.13.0 to solve several GUI issues.

To customize the ScrapBook directory, use the multi-ScrapBook feature. 

First, enter the "Manage" window:
![001](https://cloud.githubusercontent.com/assets/531417/18225174/787701f4-721f-11e6-811f-0aff563bde1e.jpg)

And then create a new ScrapBook and define its data directory:
![002](https://cloud.githubusercontent.com/assets/531417/18225186/a710b42e-721f-11e6-8a57-49825da1106a.jpg)

Now you can pick the ScrapBook as well as use the corresponding directory to store data:
![003](https://cloud.githubusercontent.com/assets/531417/18225189/ac81c934-721f-11e6-90b2-5c6164e6d948.jpg)

@jdunn0 We did have considered adding a button for Manage window in the Organize panel, but Manage window is not sufficient for changing the ScrapBook data directory—the user still have to pick the added ScrapBook entry to use it— and we still need another good design for users who don't know much except for the Options window.

**Comment by mrdc** [comment]
oh, thank you for such a detailed explanation!
