### ISSUE TITLE
again default link depth 0 in save as widow

### ISSUE THREAD

**Issue by treaki** [danny0838/firefox-scrapbook#155]
Hi,

in the original scrapbook version there was everytime i choose to save a page as the depth of links to follow set to 0 (which was a bunch of (socalled) radiobuttons and not a textfield back then), now when i use that in scrapbook x it is set to the last value, but ive got used to that behavior, so could you please add an option where that value is 0 by default?

thanks in advance and keep up the good work

**Comment by danny0838** [comment]
The behavior in legacy ScrapBook that save (capture) options except the depth level are persisted has been changed since it's rather inconsistent confusing. We probably are not going to change this back for now. 

Though the save detail dialog still has many issues (e.g. #136) and may be largely redesigned in the future. We may consider this as a part to be redesigned.

**Comment by treaki** [comment]
then dont switch it now back (after others now got used to the new behavior) but add a setting that is default disabled to mime the old behavior. like 

[ ] set follow links depth everytime to 0

thanks

**Comment by danny0838** [comment]
This should have been fixed since 1.14.0rc1, which no more save dialog settings unless `Remember current options` is checked. See #158.
