### ISSUE TITLE
Display 'Containing Folder' column in search results/manage mode

### ISSUE THREAD

**Issue by nodiscc** [danny0838/firefox-scrapbook#173]
Hi, how can I display a "Containing Folder" column in manage mode/in search results?

I use to search page titles to find articles relevant to a particular keyword, eg search for `Python`, I wish a `Containing folder` column was displayed, so I could easily spot items that are not in the correct folder (eg. `Documentation/Python/` folder), select them, move them...

I guess the columns are defined here: https://github.com/danny0838/firefox-scrapbook/blob/master/chrome/content/scrapbook/manage.xul#L71 but hadn't time to investigate further

Any help is welcome, thanks.

**Comment by danny0838** [comment]
The "Containing Folder" is not a property of an RDF item like "title" or "id" but is implicitly expressed in the RDF data tree, and thus we cannot get it listed without changing the fundamental code structure. Additionally, getting the containing folder of an RDF item is a rather expensive work, and therefore listing it like other RDF property would probably cause a performance issue.

Due to above reasons, we are unlikely to implement this feature. For your need you could perform a fulltext search instead. The fulltext search cache already includes the containing folder for all indexed items and thus the containing folder can be easily listed. If you only want to filter the title, you can use a search command like `title:<your keyword>` (see [our wiki page](https://github.com/danny0838/firefox-scrapbook/wiki/Features#search-data) for detail).

**Comment by nodiscc** [comment]
Thank you, `chrome://scrapbook/content/result.xul?q=title%3APython` works for this purpose, the results are displayed along with their containing folder when doing a full text search (unlike search on title only). Using the `title:<your keyword>` further refines results. It make it very easy to reorganize items.

Closing since this actually solves my problem.
