### ISSUE TITLE
Does not detect URLs starting with hashtag #

### ISSUE THREAD

**Issue by jkalmus** [danny0838/firefox-scrapbook#178]
I wanted to use Scrapbook to download a few pages from a webapp https://cookidoo.pl/vorwerkWebapp/ , but Scrapbook doesn't seem to find most of the URLs on the page. I found that it finds only URLs starting wit http... such as : https://cookidoo.pl/vorwerkWebapp/help
But it doesn't find URLs starting with a hashtag such as in the following HTML code : 

`<a data-ng-href="#/recipe-chips/8833350402049/bundle" title="APETYT NA WEGE" href="#/recipe-chips/8833350402049/bundle">`

I tried a Firefox add-on named Link Gopher, which is able to find all links on a page, including the ones with a hashtag. 
Would be nice if Scrapbook could detect all the links on a webpage as in Link Gopher.

**Comment by danny0838** [comment]
URLs that are different only in hash tag are considered the same file, and the hash tag only means different specific part of the file. The web page you provided uses a javascript to generate different content for that page with hash tag, you'd have to check the "Scripts" to make the "page switching" effect of the original page to work right, but it may cause some unpredicted issue since the script are not guaranteed to work in a different context.
