### ISSUE TITLE
e10s and webextentions

### ISSUE THREAD

**Issue by 12sunflowers** [danny0838/firefox-scrapbook#209]
Hi!) I am from here https://addons.mozilla.org/ru/firefox/addon/scrapbook-x/reviews/859391/
Thanks for quick answer.
I am right understand that after FF 57, Scrapbook totally do not work?
How we can push Mozilla to give suitable API components, to make Scrapbook compatible with Webextentions and e10s?

**Comment by danny0838** [comment]
Yes, if Mozilla really honors its plan in Firefox, ScrapBook X will no more work on it.

Implementation of new APIs for the WebExtension system has been requested (by I and other addon developers) for quite a long time, but sadly Mozilla seems not taking care about it (e.g. [1246236](https://bugzilla.mozilla.org/show_bug.cgi?id=1246236), [1214373](https://bugzilla.mozilla.org/show_bug.cgi?id=1214373), [1266960](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960)). If such poor condition persists, ScrapBook X will simply die forever, unless someone finds a way to make ScrapBook X work using such limited WebExtension API, to write ScrapBook X using a different framework, or so.

**Comment by 12sunflowers** [comment]
If Scrapbook die this is be very sad(
We do not have any alternative to Scrapbook?

PS Could you share your experience? What browser you will be use after FF57? And how you save and organize web pages?
PPS after big bad things from mozilla(i mean webextentions without alternatives) i found simple but not comfort solution - save full page(Ctr+s) and zip(html+folder)

**Comment by danny0838** [comment]
Whether there is an alternative depends on which features you are focusing:
- for whole web site capture, HTTrack probably works better than ScrapBook.
- for selectively cropping parts of the current web page, Evernote could work well.
- for capturing the current web page into a single "archive" file, a Chrome extension Single File could work; and for some people, saving the web page into a PDF file works.

I am not sure what to go in the future currently. If FF 57 really kills ScrapBook, we can possibly stick to FF56, switch to forks of Firefox (such as Pale Moon, although the current version still has many issues). It is possible to write a ScrapBook using a Firefox-and-Chrome-WebExtension-compatible way if we sacrificing several features in the current ScrapBook X. It is also possible to write a web page capturing script using Python or Node.js, but many features will be different from the current ScrapBook X.

**Comment by 12sunflowers** [comment]
Thanks for reply!
-HTTrack is good thing for sites, yea.
-Evernote? Good but proprietary.
-"archive"? Good but Firefox dot build-in function save to mht (MAFF extention not compatible with e10s)
-save to PDF? Good too, but it good working only on simple sites. On other saved pages PDF look very bad(

Palemoon. Good escape. But it develop very few people. And many FF addons do not work with Palemoon. 
Do you believe only Pale Moon it's our escape in this situation? Palemoon survive?

**Comment by jccalhoun** [comment]
As an academic who relies on scrapbook for my research this is sad news. Is there anything we users can do to encourage Mozilla to implement the necessary apis?

**Comment by 12sunflowers** [comment]
May be petition? Or open letter? With suggestions.

**Comment by alphapapa** [comment]
> May be petition? Or open letter? With suggestions.

I wish you all luck if you try, but I fear your time would be wasted.  Mozilla is well aware of the extensions that will be rendered completely inoperative by the removal of XUL.  They simply do not care.  The community has been pleading with them for years, but they continue to plunge forward, full-speed-ahead.  

If you are lucky, they will implement *some* of the needed APIs to recreate *some* of the features that currently exist, *someday*.  But even if they do that, there's no guarantee they will ever implement any other APIs in the future, ones that might be necessary to implement new features.  In other words, the extension will be held hostage to whatever Mozilla deigns to implement.  

As others have pointed out, if Firefox had been this way from the beginning, extensions like AdBlock, NoScript, RequestPolicy, etc, would probably never have been created in the first place--how could they have been, if their authors had had to beg Mozilla to implement not-yet-created APIs just so the author could *experiment* with their idea?  Throwing away XUL and using WebExtensions is like building with a handful of LEGO pieces that you have to beg for instead of the full range of pieces.

The best way forward, in my opinion, is to put our support behind Pale Moon.  They are committed to supporting XUL.

**Comment by ertyz** [comment]
> We do not have any alternative to Scrapbook?

For now I know only [Zotero 5](https://forums.zotero.org/discussion/comment/267549#Comment_267549) It's work on win/linux/mac, firefox/chrome/safari. [Opensource](https://github.com/zotero/zotero/milestones/5.0) also.

p.s. don't even try Evernote. It's broke markup and styles when scrapping. And heavy lagging on big pages. And now you allow to use only two devices at free version.

**Comment by ertyz** [comment]
> Mozilla seems not taking care about it

Someone can write very simple html-server receiver (on node.js for example).
Scrapbook can send all pages to this local server, and this server can store data on the local drive.
This is solved problems with no essential api for datastore in webextensions, right?

**Comment by danny0838** [comment]
@ertyz Yes, this is a potential approach to workaround the local file access issue. However, this requires the user to install a node.js app, which is a lot more complicated than installing a Firefox addon alone. Additionally, the requirement of node.js makes it impossible to work on mobiles.

**Comment by shishi** [comment]
I started use Pale moon for only scrapbook, and it seem work fine!

I backuped up Pale moon offline instarller and scrapbook's xpi, so it's ok for now.

@danny0838 Are you going to maintenance scrapbook x for Pale moon or Waterfox?

**Comment by Fixer-007** [comment]
Scrapbook is must have. Mozilla Firefox still has no mht support :( WE alternatives are not complete or good enough.

**Comment by danny0838** [comment]
Close this issue since the policy is clear now: We won't add support of e10s and WebExtension for ScrapBook X. For WebExtension "port", use [Web ScrapBook](https://github.com/danny0838/webscrapbook).
