### ISSUE TITLE
Search Folder Titles? Reveal folder location in "properties"? Search contents of a single folder?

### ISSUE THREAD

**Issue by websternyc** [danny0838/firefox-scrapbook#214]
**Search Folder Titles?**
I organize scrapbook files into folders. However, with many folders, I am unable to search just the folder names to find the folder I want.

**Reveal folder location in "properties"?**
In the "properties" of any file, I am unable to learn in which folder the file is located. This makes organizing by folders somewhat less useful. 

**Search contents of a single folder?**
In a search I do not want to search the entire tree; I want to limit the search to the contents of a single folder (or selection of folders).

**Comment by danny0838** [comment]
1\. Please separate each issue into different threads so that we can track each of them with better detail.

2\. We don't support a direct search for folders due to many conventional issues. A workaround is to create a note page and convert it into a folder, then search for the title (or content, ID, or other metadata) of the note page.

3\. There is already a "Folder" entry in the properties dialog.

![default](https://cloud.githubusercontent.com/assets/531417/26136878/21d8ecd6-3af1-11e7-90ea-1558889ec93b.png)

4\. You can right click on a specific folder and use "Manage" to open a dialog at that folder level, then search in it.
![default](https://cloud.githubusercontent.com/assets/531417/26136991/dc5badb4-3af1-11e7-8dea-52fd8ef99236.png)
![default](https://cloud.githubusercontent.com/assets/531417/26137008/f7883c10-3af1-11e7-98ac-9fe5121c6693.png)
