### ISSUE TITLE
javascript:void(0); linked pages not captured

### ISSUE THREAD

**Issue by vilasram** [danny0838/firefox-scrapbook#228]
I'am trying to download exam question & answers from "https://www.meritnation.com/", but i could capture only the first page. I have used all possible options. please guide me.

**Comment by danny0838** [comment]
"javascript:void(0);" is not a real page but something generated via javascript. You can try saving javascripts by checking "scripts" in the save details dialog and see if it works. If it still doesn't work, its probably because the javascript is bound tightly with the website and cannot work after downloaded.
