### ISSUE TITLE
Multiple selection support in the main sidebar

### ISSUE THREAD

**Issue by danny0838** [danny0838/firefox-scrapbook#23]
As [here](https://addons.mozilla.org/zh-tw/firefox/addon/scrapbook-x/reviews/642456/) mentioned, multiple selection in the main sidebar is requested. 

Currently we have support of multiple selection and manipulation in the "Manage" window. However, due to a conflict on "Open in a new tab" and "Multiple selection" for Shift/Ctrl + click, multiple selection support in the main sidebar is pending for further investigation.

What should we do?

1. No multiple selection. Keep the current "click = open", "shift/ctrl + click = open in new tab". (ScrapBook Plus 1.9.24.40b3 behavior)

2. Add multiple selection. Keep the current "click = open", "shift/ctrl + click = open in new tab + multiple selection". Neglect the unintuitive behavior that shift/ctrl + click opens the clicked item. (ScrapBook 1.5.11 behavior)

3. Add multiple selection, "click = open", "shift/ctrl + click = multiple selection". Cancel the feature of "shift/ctrl + click" for open in the new tab (alternatives: right-click > [Open in new tab], and middle-click if the mouse support is available).

We need your feedback for this. What do you think about this? Do you have another good idea?

**Comment by Misymonds** [comment]
(Please excuse my bad english): I need multiple selection support in the main sidebar too. And its very important for me in my way to work with scrapbook. But not the "shift/ctrl+click=multiple selection" or the "ctrl+click=multiple selection" (these are for my way to work less important functions). I normally use (and that does'nt work in the sidebar of Scrapbook X - but in the manage window it does - in Scrapbook by Gomita also in the sidebar) to hold down the shift-key und go down or up with the cursor-keys. My problem is that there is currently no way anywhere for a multiple selection in the sidebar. At least i didn't found a way to do this. That is almost a criterion for exclusion to use Scrapbook X - but not really :-).
Scrapbook is one of my most favorite apps - i love it very much - i just cannot live without :-) And Scrapbook X seems on the whole meanwhile the better choice as Scrapbook by Gomita  - thank you very much for your work, it makes my life a little a better...

**Comment by BrenBarn** [comment]
Personally, I do not like the behavior that a single click opens the page.  When I see something like a list of items in a sidebar, I want to click to *select* an item, not actually do anything with it, just like I would in a file explorer or the like.  So I would propose:

* click = select
* double-click = open
* ctrl/shift+click = multiple select
* ctrl/shift+double-click = open in new tab

Ultimately I think the best thing is to make it an option.  Let users choose the behavior of each click/key combo.

**Comment by Kerenok** [comment]
Agree with BrenBarn proposal on the mapping of keys to actions. After years of using Scrapbook, no easy multiple selection in main sidebar is preventing me from shifting to Scrapbook X.

**Comment by pascallothar** [comment]
Hello @danny0838 ,

I could not say things in a better way than BrenBarn did. I agree with all the points he mentionned.

But, I have to mention that, for **_Mac OS X_**, it would be:

- `click` = select
- `double-click` = open
- `cmd/shift+click` = multiple select

- `cmd/shift+double-click` = open in new tabS (meaning for several selected tabs)
- `cmd+double-click` = open in a new tab (meaning for a single selected tab)

**Comment by danny0838** [comment]
This feature was implemented in 1.13.0b6 and had some fixes in [1.13.0b7](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0b7). Feel free to try on it and give us a feedback.

Basically we added an option "Use manage mode in the sidebar", which makes the sidebar work just like the manage window. Meanwhile, we have modified several key and mouse behaviors for some reason. Here is a simple list.

### ScrapBoook 1.13.0b7

#### In the sidebar (non-manage mode)
* `LeftClick` (on twisty): Toggle folder.
* **`LeftClick`: Open item. Toggle folder.**
* **`Ctrl/Shift+LeftClick`: Open item in new tab. Toggle folder.**
* `MidClick`: Open item in new tab.
* **`DblClick`: Toggle folder.**
* `Enter`: Toggle folder. Open item.
* `Ctrl/Shift+Enter`: Toggle folder. Open item in new tab.
* **`Space`: Open item.**
* **`Ctrl/Shift+Space`: Open item in new tab.**
* `Up`: Move up.
* `Down`: Move down.
* `Left`: Collapse folder. Move to parent item.
* `Right`: Expand folder. Move to first child item.

#### In the "Manage" window (or sidebar in manage mode)
* `LeftClick` (on twisty): Toggle folder.
* **`LeftClick`: Select item.**
* **`Ctrl+LeftClick`: Add item to selection.**
* **`Shift+LeftClick`: Add items to selection.**
* `MidClick`: Open item in new tab.
* `DblClick`: Toggle folder.
* **`DblLeftClick`: Open item.**
* **`Ctrl/Shift+DblClick`: Open item in new tab.**
* `Enter`: Toggle folder. Open item.
* `Ctrl/Shift+Enter`: Toggle folder. Open item in new tab.
* **`Space`: (No effect.)**
* **`Ctrl+Space`: Toggle item from selection.**
* `Up`: Move up.
* **`Ctrl+Up`: Move up while keeping current selection.**
* **`Shift+Up`: Move up and add it to selection.**
* `Down`: Move down.
* **`Ctrl+Down`: Move down while keeping current selection.**
* **`Shift+Down`: Move down and add it to selection.**
* `Left`: Collapse folder. Move to parent item.
* `Right`: Expand folder. Move to first child item.

#### In the folder picker window
* `LeftClick` (on twisty): Toggle folder.
* `LeftClick`: Select item.
* `DblClick`: Toggle folder.
* `Enter`: Toggle folder.
* `Up`: Move up and select it.
* `Down`: Move down and select it.
* `Left`: Collapse folder. Move to parent item and select it.
* `Right`: Expand folder. Move to first child item and select it.

## Notes:
* "Twisty" is the small triangle aside a folder item to toggle a folder and indicate its status.
* DblClick fires on pressing any mouse button twice, including left, middle, or right. Also, the two single clicks have effect before the dblclick fires.
* The full support of Mac could be delayed since there are still some unresolved and unrecognized issues.

**Comment by pascallothar** [comment]
_You wrote (for example) «_
### ScrapBoook 1.13.0b7
**In the sidebar (non-manage mode)**
	•	
	•	**`LeftClick`: Open item. Toggle folder.**
 	•	

_» in bold, and «_
### ScrapBoook 1.12.36 (for comparison)
**In the sidebar**
	•	
	•	`LeftClick`: Toggle folder. Open item.
	•	 

_» not in bold._

I am not sure to understand the difference. I guess you were in an edition task, but that you forgot to finish it. Didn't you? Or should I take vitamins? :-) . I guess you wanted to say something like:
« _On item or "non-folder-type folder", does open it. On standard folder, does toggle it._ »,
didn't you?

---

You said « _The full support of Mac could be delayed since there are still some unresolved and unrecognized issues._ ». But I can say that, thanks to you, it is already better :-) . Regarding the current topic, does it help you to know that `Cmd key` == `Apple key` == HARDWARE equivalent of `Windows key` (actually, there is no problem to put a Windows keyboard on an Intel Mac)? Though if it comes to functionality, Mac use usually the `Cmd/Apple/Windows key` where Windows would use `Ctrl key` (even if HARDWARE equivalent of `Ctrl key` is `Ctrl key` itself).

You said « _`DblClick` fires on pressing any mouse button twice, including left, middle, or right._ ». Do I have to understand that, on Windows, if you `DblRightClick` or `DblMidClick` and item, the result is the same as if you would `DblLeftClick` it? Than it is not the same on Mac, as you can see below. But I don't see any problem there, since usually people don't use `DblRightClick` or `DblMidClick` on items. Do they?

You said « _Also, the two `single clicks` have effect before the `dblclick` fires._ ». I guess you meant that, for example, when you `Shift+DoubleLeftClick` an item in 1.12.36, it will open it twice in two tabs. Yes, it sounds to me to be normal.

---

Following is the (detailed) test on **ScrapBoook 1.13.0b7** on my **Mac**.

I have installed a external mouse to test the `Middle-Click`.

**Note:** Because I am on Mac, I use `Cmd` key where you usually use `Ctrl`.

---

In the sidebar (non-manage mode):

- `LeftClick (on twisty)`: Toggle. _( == OK)_
- `LeftClick`: Open item or "non-folder-type folder" in the CURRENT tab. Toggle standard folder. _( == OK)_
- `Cmd+LeftClick`: _Same as `LeftClick`, but SHOULD do:_ Open item or "non-folder-type folder" in a NEW tab. Toggle standard folder.
- `Shift+LeftClick`: Open item or "non-folder-type folder" in a NEW tab. Toggle standard folder. _( == OK, `   ***`but why not to open in a new WINDOW, since `Cmd+LeftClick` (or `Ctrl+LeftClick` on Windows) already open in a new TAB?)_
- `MidClick`: Open item or "non-folder-type folder" in a NEW tab. Toggle standard folder. _( == OK)_
- `DblLeftClick`: Open item in the CURRENT tab. Toggle and open "non-folder-type folder" in the CURRENT tab. Toggle standard folder. _( == OK)_
- (`DblMidClick`: Open item in 2 new tabs. Toggle and open "non-folder-type folder" in 2 new tabs. Toggle standard folder. _( == Not that bad)_)
- (`DblRightClick`: Contextual menu on items. Contextual menu + toggle "non-folder-type folder" or standard folder. _( == Not bad)_)
- `Enter`: Open item in the CURRENT tab. Toggle "non-folder-type folder" _(I don't know if it SHOULD OR NOT open it)_. Toggle standard folder.
- `Cmd+Enter`: Open item in CURRENT tab _(SHOULD be in a NEW one)_. Open "non-folder-type folder" in CURRENT tab _(SHOULD be in a NEW one) (I don't know if it SHOULD OR NOT toggle it)_. DOESN'T toggle standard folder _(You said that, on Windows, it does)_.
- `Shift+Enter`: Open item in NEW tab. Open "non-folder-type folder" in NEW tab _(I don't know if it SHOULD OR NOT toggle it)_. DOESN'T toggle standard folder _(You said that, on Windows, it does). `   ***`(Could open in a new WINDOW (see above: WINDOW vs TAB))_
- `Space`: Open item or "non-folder-type folder" in CURRENT tab. Nothing on standard folder. _( == OK)_
- `Cmd+Space`: Open item or "non-folder-type folder" in CURRENT tab _(SHOULD be in a NEW one)_. Nothing on standard folder.
- `Shift+Space`: Open item or "non-folder-type folder" in NEW tab. Nothing on standard folder. _( == OK, `   ***`but see above: WINDOW vs TAB)_
- `Up`: Move up. _( == OK)_
- `Down`: Move down. _( == OK)_
- `Left`: Collapse folder. Move to parent item. _( == OK)_
- `Right`: Expand folder. Move to first child item. _( == OK)_

In the "Manage" window (or sidebar in manage mode):

- `LeftClick (on twisty)`: Toggle. _( == OK)_
- `LeftClick`: Select. _( == OK)_
- `Cmd+LeftClick`: Add/Remove one item (or ... ) to selection. _( == OK)_
- `Shift+LeftClick`: Add multiple items (or ... ) to selection. _( == OK)_
- `MidClick`: Open item or "non-folder-type folder" in NEW tab. On standard folder, only select._( == OK)_
- `DblLeftClick`: Open item in CURRENT tab. Toggle "non-folder-type folder" _(DOESN'T open it in the CURRENT tab (It SHOULD, since there is no other DIRECT way to open it with only the mouse)))_. Toggle standard folder.
- (`DblMidClick`: Open item in 2 new tabs. Toggle and open "non-folder-type folder" in 2 new tabs. Toggle standard folder. _( == Not that bad))_
- (`DblRightClick`: Contextual menu on items. Contextual menu + toggle "non-folder-type folder" or standard folder. _( == Not bad))_
- `Cmd+DblLeftClick`: Open item in CURRENT tab _(SHOULD be in a NEW one)_. Toggle "non-folder-type folder" _(DOESN'T open it in a NEW tab (It SHOULD, since there is no other DIRECT way to open it with only the mouse)))_. Toggle standard folder. _(NOTE: If some other item(s) were already selected, other items than the opened/toggled one will be selected afterwhile, making it difficult to see which one was opened/toggled. Since there is ONLY ONE opened/toggled, it would make more sense if only one would remain selected.)_
- `Shift+DblLeftClick`: Open item in NEW tab. Toggle "non-folder-type folder" _(DOESN'T open it in a NEW tab (It SHOULD, since there is no other DIRECT way to open it with only the mouse)))_. Toggle standard folder. _(see NOTE above) `   ***`(see above: WINDOW vs TAB)_
- `Enter`: Open item in the CURRENT tab. Toggle "non-folder-type folder" _(I don't know if it SHOULD OR NOT open it)_. Toggle standard folder.
- `Shift+Enter`: Open item in NEW tab. Open "non-folder-type folder" in NEW tab _(I don't know if it SHOULD OR NOT toggle it)_. DOESN'T toggle standard folder _(You said that, on Windows, it does). `   ***`(Could be in a new WINDOW (see above: WINDOW vs TAB))_
- `Cmd+Enter`: Same than `Shift+Enter`, but in CURRENT tab _(SHOULD be in a NEW one)_.
- `Space`: (No effect) _( == OK)_
- `Cmd+Space`: Toggle item from selection. _( == OK)_
- `Up`: Move up. _( == OK)_
- `Cmd+Up`: Move up while keeping current selection. _(Works. But on Mac, you have no clue on which item your are, unless you calculate it. Perhaps, on Windows, is there something like a background color (other than blue or white) to see where you are? Anyway, since I only use the clicks and the modifiers.)_
- `Shift+Up`: Move up and add it to selection. _( == OK)_
- `Down`: Move down. _( == OK)_
- `Cmd+Down`: Move down while keeping current selection. _(As I mentioned it for `Cmd+Up`, I am able to use `Cmd+Space/Up/Down` and `Shift+Up/Down` to make a "complex" selection, but it is training my memory and my eyes :-D_
- `Shift+Down`: Move down and add it to selection. _( == OK)_
- `Left`: Collapse folder. Move to parent item. _( == OK)_
- `Right`: Expand folder. Move to first child item. _( == OK)_

In the folder picker window:  _( All are OK)_

- `LeftClick (on twisty)`: Toggle folder.
- `LeftClick`: Select item.
- `DblClick`: Toggle folder.
- `Enter`: Toggle folder.
- `Up`: Move up and select it.
- `Down`: Move down and select it.
- `Left`: Collapse folder. Move to parent item and select it.
- `Right`: Expand folder. Move to first child item and select it.

**Comment by Kerenok** [comment]
Thanks to @danny0838 , since  #d65ab60, I can know shift to Scrapbook X. Good work!

**Comment by danny0838** [comment]
We at least have basic support for multiple selection in the side bar. There might be details that can be improved, though, and it's welcome to provide more feedback about this.

**Comment by BrenBarn** [comment]
Has the version with this fix been officially released?

**Comment by danny0838** [comment]
It has been included in beta version ScrapBook X 1.13.0b6 and is likely to be included in 1.13.0 unless there is an unresolvable critical issue related to it found.

**Comment by BrenBarn** [comment]
So I guess that's a no then.  Any idea when 1.13.0 will be released?

**Comment by danny0838** [comment]
@BrenBarn The release date was originally scheduled on 8/1, and we are overdue now due to several newly discovered issues and unresolved issues. You can see [v1.13.0 milestone](https://github.com/danny0838/firefox-scrapbook/milestone/1) for our plan and the list of pending issues.

**Comment by pascallothar** [comment]
@danny0838 ,

During my use of Scrapbook X, I have noticed that you corrected certain behaviors for the clicks in the sidebar, so I made a new test to compare with the previous one. I have linked the result FYI.

---

When I was in the page `about:config`, I have seen that the "**_User_**" can add some new custom entries.

![about config](https://cloud.githubusercontent.com/assets/20140037/17468287/13801812-5d16-11e6-90e5-827b837b4f49.png)


I am not sure what it is for. But I was wondering if it could be used to assign new values to some "Constants" in Scrapbook X. Are the clicking behaviors implemented in a way that some kind of Constants are defined? And if so, are those Constants accessible from `about:config`?

---

If it is not possible to customize this way, would you mind to re-think the behavior of the `DblLeftClick` on "**_non-folder-type folder_**" in "**_Manage mode_**"?

For the moment, in "Manage mode", the only way to open a "non-folder-type folder" with only the mouse, is to open the contextual menu by right-clicking and then choose "Open" or "Open in New Tab". The intuitive behavior would be to open it by double-clicking it, as for a normal item.

For the moment, double-clicking it will toggle Expand/Collapse the "non-folder-type folder" as for a normal folder. Since we have twisties to do that, it is unnecessary.

Even if it is not a problem to let the double-click toggle a standard folder (even if it is redundant with the click on the twisty), the right behavior for a "non-folder-type folder" would be to open it in the CURRENT tab (and in a NEW tab if `Cmd` or `Shift` is down) and NOT to toggle it at all. Because, when a "non-folder-type folder" is expanded (collapsed) and you double-click it to open it, you just want to open it and not to see the "non-folder-type folder" collapsed (expanded) afterwards. You would need to click once more on the twisty to bring it to its previous state.

---

![clicks](https://cloud.githubusercontent.com/assets/20140037/17469727/731fecb6-5d25-11e6-94f6-4a81986523e0.png)

**Comment by danny0838** [comment]
@pascallothar Double click to toggle a folder in a data tree is a behavior natively provided by Firefox and it would be more difficult to block the behavior.

Double-click to toggle a folder is a behavior widely implemented in most file browser in the OS, which also has a twisty for folder expanding. Also, in the context of a manage window the user is unlikely willing to open a page, so double-click to toggle folder can still be more expected here. 

Maybe it is less desirable for the sidebar in manage mode, but changing the behavior only for the sidebar causes an inconsistency and may confuse the user. We'll keep current design until we come up with a more comprehensive solution.

**Comment by pascallothar** [comment]
> Double-click to toggle a folder is a behavior widely implemented in most file browser in the OS, which also has a twisty for folder expanding.

Yes, but they don't have to deal with the "non-folder type folder" witch is a improvement they don't need to use. The **_purpose_** of the "non-folder type folder" is to be used **_ALSO_** as a standard item would be.

> Also, in the context of a manage window the user is unlikely willing to open a page, so it can still be more desirable here.

The "non-folder type folder" is a NEW and uncommon feature, so we cannot talk about a change in their habits. In the "manage window", double-clicking a standard item will open a page, so what is the difference?

> Maybe it is less desirable for the sidebar in manage mode,

As you say, it is less desirable. But what is of more importance is that there is no other easy way to open the "non-folder type folder" as a standard item.
I would say, that, when in the sidebar, when going through the items (to remember their actual content), it is contra-intuitive and even less convivial to have to open the "non-folder type folder" ITEMS in a different way than the standard ITEMS.

> Double click to toggle a folder in a data tree is a behavior natively provided by Firefox and it would be more difficult to block the behavior.

Oh, I see.
But, do you think it would be possible to choose with `about:config` to "remap" or "redirect" the `Cmd+DblLeftClick` to `Cmd+Enter` (and the same for `Shift`) with something like (very approximative!!!) `OnDblClick == Press(Cmd, Enter)`? Because `Cmd+Enter` and `Shift+Enter` are doing exactly what I would expect of `Cmd+DblLeftClick` and `Shift+DblLeftClick`.

**Comment by pascallothar** [comment]
`DblLeftClick`, `Cmd+DblLeftClick` and `Shift+DblLeftClick` on a _"non-folder type folder"_ now work perfect.

Awesome!

Thank you very much @danny0838
