### ISSUE TITLE
[enhancement] Saving Favicon on Bookmarking

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#242]
It is not a priority at all, but when I bookmark a link, the Favicon is not saved. It makes the indenting difficult to understand. Could it be possible to save the site favicon or, if to difficult to implement, to save a default favicon?

Have a nice day,
Pascal.

**Comment by mseliger** [comment]
Yes, it is somewhat strange. For me, e.g. the favicon is not shown in the tree, but it is stored in the .dat field and it is shown, when you open the properties of the bookmark.
Here a favicon, which is not shown in the tree, but in the properties of the bookmark (from the .dat file):
icon	https://www.databasejournal.com/favicon.ico#-moz-resolution=19,19
source	https://www.databasejournal.com/features/article.php/3593466/MS-SQL-Series.htm
And here a favicon, which is shown in the tree and in the properties of the bookmark:
icon	https://assets-cdn.github.com/favicon.ico#-moz-resolution=19,19
source	https://github.com/danny0838/firefox-scrapbook/issues/242
(link to this entry)

**Comment by danny0838** [comment]
Due to the ancient structure reason it is currently not viable to change the behavior. It seems that the indentation is ok in the built-in rdf tree even if a favicon is missing, but the output page gets the indentation messed up, which is something we can fix. (Done in [1.14.3](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.14.3))
