### ISSUE TITLE
Saving State, Instructions, Options Error

### ISSUE THREAD

**Issue by siennk** [danny0838/firefox-scrapbook#249]
1) Some sites take longer to save. Sometimes I don't even know if pages are saved after an hour because they take so long. So is it possible to add a progress bar or something to show just how far along the saving process is for each page?

2) Is there any way to make the instructions/guide a bit more clearer? Or more dumbed down? I tried reading through multiple times but still got lost in translation in multiple parts.

3) I don't know if it's the extension's fault or if it's something on my end, but I can't for the life of me get the options/preferences window to open all the way. All I can ever see is one line. If it matters, I am using Firefox on Mac.

**Comment by danny0838** [comment]
It's extremely difficult to track separated issues in a single thread. Please create new thread for issue 2 & 3 and edit this issue to leave the first one in 7 days. If you don't, we'll edit for you and only the first issue will be left.

For issue 1:  Please provide the web page URLs in issue. And tell whether it always happens or occasionally happens. If possible, please check which factor triggers the issue. You can also try using a clean profile and try disable other addons and see if the issue persists.

For issue 2 (when you create a new thread for it): Please be more clear about which instruction/guide you are mentioning, the app or the wiki or whatever else? Sometimes it would be better to provide a screenshot. Besides, what is the language you speak?

For issue 3 (when you create a new thread for it): Please provide your OS version, Firefox version, and ScrapBook X version. Please provide screenshots illustrating it, since we really have no idea about what happens on your computer and what you see.
