### ISSUE TITLE
problems to manage and read saved snippets / pages

### ISSUE THREAD

**Issue by frondizi** [danny0838/firefox-scrapbook#257]
Hello,
in december i installed scrapbook web in Firefox Quantum 57.0x  in the place of the no longer working Scrapbook extension by Gomita. 
i just tried to start to use it but i am not able to save nothing because when i try to save a selected section of a web page in the window of the running process of capture i get a series of download errors (error 404 for example in the main search page of Trenitalia , the main railways transport company in Italy) and i'm not able to save the portion of page in .htz format ( i guess it is set as default format in the extension)
**EDIT:**  i have been able to save, after a few seconds of freezing, to a certain location a snippet but i can't understand the same how to read it back on Firefox and to manage the saved pages by your extention.  in the precedent extention there was a dedicated list of saved pages and you could also open the related column to manage them on the left of window browser. 

I have to say that i don't feel at ease at all with this extention compared to the the old Scrapbook , your extention has a very difficult menu options with a lot of technical terms and parameters that the final user doesn't have to know.  The precedent before saving a page opened an option window that was easy to understand at glance. You was able quickly to understand every time what elements it was going to save in the single capturing session basing on your settings.    
New platform of Firefox in general created the effect of an earthquake , a real negative revolution about the compatibility of the extentions. 

Also i don't have yet found someone that explains me how to use old Scapbook saved pages to manage them and browse them in Firefox Quantum.  Is it possible to import and manage them with your extension? 
Dimitri

**Comment by danny0838** [comment]
This repository is for [ScrapBook X](https://addons.mozilla.org/firefox/addon/scrapbook-x/). If you are mentioning about [Web ScrapBook](https://addons.mozilla.org/firefox/addon/web-scrapbook/), please post this issue [here](https://github.com/danny0838/webscrapbook/issues) so that we can track it correctly.

For how to read .htz files see the documentation [here](https://github.com/danny0838/webscrapbook/wiki/View).

There is a tooltip when the mouse is hovered over an option, you can read it for more explanation. For example:
![default](https://user-images.githubusercontent.com/531417/34819045-a2a3100e-f6f7-11e7-991b-601b6fcdb3ef.png)

**Comment by danny0838** [comment]
Close invalid issue.
