### ISSUE TITLE
Note Page title not set

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#51]
Legacy Scrapbook Note takes its title as the first line of the note.
Note Page doesn't do this automatically.

**Comment by danny0838** [comment]
This is the normal and default behavior since note pages are not notes.

You can use special attributes to make note page title update automatically according to an HTML DOM content, for example write `<h1 data-sb-obj="title-src">Your page title</h1>` and ScrapBook X will update the note page title on saving the page once the content of the h1 element is modified.

Furthermore, you can modify `notex_template.html` in the ScrapBook directory so that all newly created note pages in the ScrapBook use the default template. Here's an exmple:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title data-sb-obj="title"><%NOTE_TITLE%></title>
  <link rel="stylesheet" href="<%SCRAPBOOK_DIR%>/common.css">
</head>
<body>
<h1 data-sb-obj="title-src"><%NOTE_TITLE%></h1>
<hr>
</body>
</html>
```

It is documented in [this wiki page](https://github.com/danny0838/firefox-scrapbook/wiki/Scheme-%28zh-tw%29), sorry for being so lazy that it's not translated to English.

**Comment by grotesque** [comment]
Thanks!!

We are now able to set the "Title" property of the Note via the h1 element.
Maybe we can use h2 element to set the URL of the Note.
