### ISSUE TITLE
Can we not search folders by name?

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#57]

**Comment by danny0838** [comment]
No. ScrapBook X doesn't support searching items which is a folder, just as most file searching engines do. Implementing such feature would be a very, very large frame rework, and could only be done in something like "ScrapBook X 2.0".

**Comment by Misymonds** [comment]
For me searching folders by name is the most missing function of Scrapbook. Since my tree(s) are very deep and large and my brain quite perforated. I currently makes workarounds by creating dummy items with the same name as the folder. But unfortunately it's a little bit inconvenient...

BTW: What I'm very missing too is a method to localize (at least this is the retranslation of the german labeling) a founded bookmark (that appears in a search result) in my folder tree. I use the function to localize a standard item very often. Sometimes I make a workaround for bookmarks as i already mentioned above.

As I mentioned already in another github issue I'm thankful for the existence of Scrapbook.

**Comment by grotesque** [comment]
My workaround for the lack of folder search in scrapbook is greping the .rdf file of that particular scrapbook. But this is very inconvenient.

A lack of "Folder search" is the only glaringly-lacking thing in scrapbook in my opinion.

> I'm thankful for the existence of Scrapbook.
Me too.

**Comment by grotesque** [comment]
> What I'm very missing too is a method to localize (at least this is the retranslation of the german labeling) a founded bookmark (that appears in a search result) in my folder tree

By localize I think you mean "locate".

What I do for this is go to properties of that bookmark in search result...there I see the folders hierarchy where the bookmark resides. Then I open folder manually.

**Comment by danny0838** [comment]
We now support "non-folder-type folders' since 1.13.05b. You can convert a note page to a folder and thus it's searchable.
