### ISSUE TITLE
output html tree 

### ISSUE THREAD

**Issue by fxshpac** [danny0838/firefox-scrapbook#71]
With latest version and auto save enabled, whenever i add a new page i expect the html tree will be updated automatically but its not. Manually triggered save does work on the other hand. Please let me know how to address this issue. Thx

**Comment by danny0838** [comment]
It seems to be an issue concerning the interaction of ScrapBook X and ScrapBook X AutoSave. We'll do further investigation on it.

**Comment by danny0838** [comment]
After a more thorough check there is no problem between ScrapBook X and ScrapBook X AutoSave.

The html tree will be upload automatically only when the ScrapBook database is closed, i.e. when the Firefox is closed or when the user switches the current ScrapBook to another path. This is because outputting HTML tree is a relatively large process and can take time and interrupt the user, and thus it does not run routinely when there is a change to the ScrapBook tree.

**Comment by danny0838** [comment]
Closed the issue due to absence of further response.
