### ISSUE TITLE
Linux drag with modifiers doesn't work

### ISSUE THREAD

**Issue by jsivak** [danny0838/firefox-scrapbook#72]
In Scrapbook Plus I was able to click the site icon (in the address bar) then press the ALT key while dragging the icon to the Scrapbook side-bar. Is this feature not supported in Scrapbook X?

Here's a link to the Scrapbook site describing the feature: http://www.xuldev.org/scrapbook/tips.php

Thanks

**Comment by danny0838** [comment]
This function is supported. I'd just tested and it worked ok.

**Comment by jsivak** [comment]
On linux? (I'm running Firefox 42.0 on Archlinux)

**Comment by danny0838** [comment]
It is tested on Windows. Although it's not likely that this feature would work different in Linux version.

**Comment by jsivak** [comment]
Hmm..  I'll have to boot a Live CD of Ubuntu or CentOS and try it..

**Comment by mseliger** [comment]
If you use CTRL (STRG) instead of the ALT then you can capture a page in the Scrapbook side-bar by dragging the site icon from the address bar.
Tested with Lubuntu 15.10 and Firefox 43.

**Comment by jsivak** [comment]
Using the CTRL key while dragging is still creating a "full download/snapshot" of the site. I'm trying to just get a "bookmark" (green text) in the Scrapbook sidebar.

If I try CTRL + SHIFT, I do see a "link" icon on the mouse (instead of the "plus" or "arrow" icons), but I"m still getting a full snapshot of the page (black text in ScrapBook sidebar, not the green "bookmark" text). This was in Archlinux, XFCE, Firefox 43.0.1..  while try the Ubuntu image later to see if it does it too.

**Comment by danny0838** [comment]
It seems that some Linux distros have system-wide function for Alt key and thus could mask the browser accesskey. Does Alt key function normally otherwise in Firefox?

**Comment by danny0838** [comment]
I tested Ubuntu Desktop using VirtualBox simulation. It seems that all modifiers, including Ctrl, Alt, Shift, are never detected for drag events (e.g. dragging the tab, dragging the address bar icon, dragging a link in the page, etc).

It seems to be an issue of Firefox core. We'll pass the issue to the development team.

**Comment by danny0838** [comment]
@pascallothar It is not clear whether this issue exists on Mac. Could you help us test?

**Comment by jsivak** [comment]
Thanks for checking this out; will be interesting if Firefox upstream has an answer.

**Comment by pascallothar** [comment]
On my Mac, it works well. No, Mac_Intosh is a bad guy, but not that bad :-D

To be more precise:
- Dragging **_tab_**, address bar **_icon_**, **_link_** in page ==> `Save`
- Dragging address bar **_icon_**, **_link_** in page with `Shift` down ==> `Save As...`
   - Does nothing on a **_tab_** (I don't know why? Perhaps because with `Shift` down, the `Click` `release` (not the `push`) is used to toggle protect/lock the tab.)
- Dragging **_tab_**, address bar **_icon_**, **_link_** in page with **_`Cmd`_** down ==> `Save As...`
- Dragging  **_tab_**, address bar **_icon_** with `Alt` down ==> `Bookmark`
   - Clicking **_link_** in page with `Alt` down and then dragging, will select text inside the link string. How interesting! I have discovered something! It will ease the highlighting of links. So, as a result, you need first to drag the link `without holding Alt`, and then on the way of dragging, begin to push `Alt` .

---

> I tested Ubuntu Desktop using VirtualBox simulation. It seems that all modifiers, including Ctrl, Alt, Shift, are never detected for drag events (e.g. dragging the tab, dragging the address bar icon, dragging a link in the page, etc).

Some Virtual Machines have issues when it comes to emulate some hardware. Even if keyboard, modifiers and MOUSE are very basic hardware, perhaps, it would be necessary to test this with a real install of Ubuntu Desktop before having this conclusion.

**Comment by danny0838** [comment]
@pascallothar Good! It seems to work right on Mac.

Firefox only detects modifier keys at the time you are dropping the item. For my PC if I hold no key when I start dragging a tab, hold Shift, and then drop it to the sidebar, capture detail is triggered, which is as expected.

I know that Virtual Machine could cause hardware issues. But since the Alt key works right in most aspects, I'd still first suspect it's a problem of Firefox. Though, more test on other Linux environments (e.g. non-GNOME desktops) may be needed.

**Comment by pascallothar** [comment]
> Firefox only detects modifier keys at the time you are dropping the item.

If I hold `Alt` when I start dragging a link, I see a green `+`. Otherwise not. If I release `Alt`, it will disappear, if I hold `Alt` again on the way dragging, it will reappear.

So wouln'd it be more correct to say that even if Firefox detects modifier keys at any time, the event triggered when the item is dropped depends of the status of the modifier at the instant when it is dropped.

I want to precise that if I tell you that, it is ONLY for the purpose to help you (Perhaps or perhaps not) to understand the behavior of Firefox if you didn't already understand everything. But, I am not an expert at all :-)

> For my PC if I hold no key when I start dragging a tab, hold Shift, and then drop it to the sidebar, a capture detail is triggered, which is as expected.

I have tried this on my Mac and it works this way too. Good to know! So even if I am not able to start a dragging when `Shift` is down, I am able to achieve it by holding `Shift` later. And I wonder if the fact of not to be able to start a dragging when `Shift` is down could be because I am using TabMixPlus which use `Shift+Click` to toggle protect/lock the tab.

**Comment by danny0838** [comment]
> > Firefox only detects modifier keys at the time you are dropping the item.
> 
> If I hold `Alt` when I start dragging a link, I see a green `+`. Otherwise not. If I release `Alt`, it will disappear, if I hold `Alt` again on the way dragging, it will reappear.
> 
> So wouln'd it be more correct to say that even if Firefox detects modifier keys at any time, the event triggered when the item is dropped depends of the status of the modifier at the instant when it is dropped.

You are right. Firefox does detect modifier keys at other time. It is ScrapBook X that only detects the modifier keys at the time of dropping to decide its behavior.

**Comment by danny0838** [comment]
@jsivak This issue seems related with the old API for drag and drop. This issue seems to be resolved after shifting to the new API in [1.13.0b12](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0b12), at least for me. Please have a test and check whether this issue resolved.

**Comment by jsivak** [comment]
Just tested with Firefox 48 on ArchLinux and it is working!  Thank you!

**Comment by danny0838** [comment]
Good. We killed another bug.
