### ISSUE TITLE
Options "Reorganize Styles" and  "Capture as HTML"

### ISSUE THREAD

**Issue by Kurtafterjim** [danny0838/firefox-scrapbook#73]
Hi Danny Lin,
your plug-in is very great! I don't  understand what's the mean of the options "Reorganize Styles" and  "Capture as HTML".
Could you help me?
Thanks!

**Comment by danny0838** [comment]
**Reorganize Styles**: If a web page links to several .css files, and when checked, all css will be parsed and merged to a single index.css file. When unchecked, all css will simply be downloaded and linked, This feature is rather limited for some rare cases, such as to capture with it unchecked as a fallback if the css cannot be correctly parsed when it is checked, or when one really wants to preserve the original css files to do something with them.

**Capture as HTML**: This option is renamed to `Capture presenting HTML for non-HTML files` in version 1.12.12 due to the vagueness for the prior title. When a non-HTML file (such as txt, js, css, xml) is opened in Firefox, if this option is unchecked, ScrapBook simply downloads the file and creates a "file" item, which preserves the original content but can hardly be indexed, searched, annotated, or edited by ScrapBook. With this option checked, ScrapBook captures the current presenting HTML (i.e. the HTML showing on the screen) and creates a "page" item, which is better managed by ScrapBook, but the original information of the file is not preserved.

**Comment by Kurtafterjim** [comment]
Thanks for your support!
