### ISSUE TITLE
Firefox Android lists SBX for download?

### ISSUE THREAD

**Issue by ChrisRoald** [danny0838/firefox-scrapbook#76]
Hi. When FF for Android listed SBX in Addons, I selected it, and clicked Download.
Obviously nothing happened as the version listed is for Laptops; I've just read GH requests on Android version.
Does the FF Addons list show non-mobile apps regardless? 
If and when, I'd be happy to pay up to £10 for a mobile version - very impressive on win/linux. C.

**Comment by danny0838** [comment]
Currently ScrapBook X does not support Firefox Android since it uses a framework very different to Firefox for PC. It would be possible that you had erroneously visited an addon page for Firefox PC and downloaded what was not intended for Android.

Thank you for the appreciation. Support for Android had been raised but it's still a very big challenge currently. Refer #9 for more detail.

**Comment by danny0838** [comment]
Close this issue since it's not really an issue and hase been no response for half year.
