### ISSUE TITLE
Create a new folder on top for "Capture all tabs"

### ISSUE THREAD

**Issue by mrdc** [danny0838/firefox-scrapbook#81]
Would be nice to place a new folder on top when pages are saved with "Capture all tabs" like with Scrapbook or Scrapbook Plus.
I've seen the option to place everything on top, but it messes with tabs being saved in reverse.

**Comment by danny0838** [comment]
You can create a new folder manually and select that folder when your are capturing all tabs.

**Comment by mrdc** [comment]
Yes, that's possible but will need extra actions: Scrapboox X -> Show in sidebar -> Create a folder -> Capture All Tabs.

**Comment by danny0838** [comment]
You can create a new folder via the `New Folder...` button in the dialog window after clicking `Capture All Tabs...` if there isn't already an appropriate one. I think it is fast enough.

![2016-01-26 22_05_53-select folder](https://cloud.githubusercontent.com/assets/531417/12582601/247a6626-c479-11e5-9ca0-2b70938e42e3.png)

**Comment by mrdc** [comment]
Oh, it looks like it is some kind of misunderstanding: when I create a folder like it's show on your picture this new folder is not placed on top of folders I have but at the bottom, so I have to manually bring it on top. With Scrapbook & Scrapbook Plus a new folder is created on top by default. That's what I was talking about :)

**Comment by danny0838** [comment]
Thank you for the clarification. Since "everything go from bottom to top or from top to bottom" is considered more rational, the "birectional behavior" of ScrapBook and ScrapBook Plus is considered too ad hoc, undesired, and somehow a bug, and we are not going to provide it. As a result, you'd have to achieve it in a rather complicated way if you really care about it, and we regret for your inconvenience.
