### ISSUE TITLE
Capture Issue and two others

### ISSUE THREAD

**Issue by githmw** [danny0838/firefox-scrapbook#82]
I just installed Scrapbook X (Ver. 1.12.17) on a Windows 7 Pro (64) bit desktop computer. This is an add-on to my Pale Moon (Ver. 26) browser. I really like the features of the program so far, and appreciate it being written and actively updated. [I  never owned Scrapbook or Scrapbook Plus]

I have three questions that I was not able ti find answers to in the Documentation  or on this forum.
1. When I open a page that I have captured, The footer bar (as shown in the 1st attachment) pops up. That bar is a bright blue color. How do I change that color to something else?
2. I have been capturing various sites just to test. Most work fine. However one does not. See the 2nd attachment. The top (#1) screenshot is what the webpage actually looks like. The bottom (#2) screenshot is what the capture looks like. You will note, as pointed to with the red arrows, several graphs are not loaded, and all say there is an error loading the file. Any idea why this is happening, and if there is any way to correct it?
3. I also have Firefox (Ver. 42) on the same computer. I would like to also have Scrapbook X work on that computer. I assume I have to install the add-on for Firefox  into a different folder than I did  for Pale Moon. Is that correct? Is there any way I can have them share the same Root folder that I set up for Pale Moon?

Thanks,

Harry

![scrapbox-footerbare](https://cloud.githubusercontent.com/assets/17102180/12869390/354b2ac8-ccec-11e5-9c22-d12a2012dcb3.png)

![scrapbookx_fitbite](https://cloud.githubusercontent.com/assets/17102180/12869391/43cf80d0-ccec-11e5-91bd-98be6da9d04c.png)

**Comment by danny0838** [comment]
1. User style is probably the way to modify it. But I haven't used it before, so I cannot guarantee whether it works.

2. Could you provide the source URL for further investigation?

3. There is generally no need to change the root folder (aka. the Profile Folder), while you can modify the ScrapBook folder path via preference options so that both applications share the same data folder. Note that you should not access the ScrapBook folder via multiple applications at the same time, or conflicts and data loss may happen.

**Comment by githmw** [comment]
Danny:

Thanks for the very prompt reply.

>>1. User style is probably the way to modify it. But I haven't used it before, so I cannot guarantee whether it works.
After some testing, I determined this is controlled not by a Windows
setting, but by Appearance Themes in the browsers. I changed what I
had, and now the color is more to my liking.

>>2. Could you provide the source URL for further investigation?
This requires a login by a Fitbit user. Go here:
https://www.fitbit.com/sleep    (ignore the warning messages)
Use the following, which is my account:
Email: hmw3@compuserve.com
Password: 8fitbit1

UNCHECK the 'Remember Me' box!  I never let the sites remember my
login information.

The screen that opens after you login is the same as #1 on the
attachment I sent previously. (The graphed data you will see is
slightly different: it is from today, whereas what I sent was from
yesterday.

When you Capture the page, you should see the same as #2 on the
attachment.

Let me know if you can determine what causes this, and if there is a
fix.

>>3. There is generally no need to change the root folder (aka. the Profile Folder), while you can modify the ScrapBook folder path via preference options so that both applications share the same data folder. Note that you should not access the ScrapBook folder via multiple applications at the same time, or conflicts and data loss may happen.

I could not figure out how to maintain the default root folder (which
for Mozilla is in a different AppData->Roaming subfolder than for Pale
Moon). But I set up a common root folder in my Documents directory,
and everything works just great. The folders and entries I added
appear on both browsers. I will try to remember to heed your warning
on accessing the Scrapbook folder from both browsers at the same time.
The only reason I have set this up this way is because some websites
work on one browser and not the other, and having your Tools->Show
Files feature will help me sort out why, since both Captures will be
able to be accessed from either Pale Moon, or Firefox.

I have been reading your Documentation as well as the Scrapbook 1.2
tutorial, which I downloaded. Their tutorial talks about a List View,
which splits the Sidebar in two: displaying folders in the top panel
and files in the bottom panel, and shows a screenshot. But I can't
figure out how to get this to work. There is no List View icon shown
in the header of my Sidebar, although their are other icons there .
Also, if I right click on a folder, List View does not appear in the
dropdown menu. But when I open the Manage window, the Sidebar icon is
there, and it seems to work fine {though it does not appear in that
folder dropdown either--not sure if it is supposed to}. Any thoughts?


Harry

**Comment by danny0838** [comment]
1.\ That's fine. Thank you for your information.

2.\ The "images" are flashes instead of embedded image files. Unfortunately, ScrapBook X cannot guarantee that all flashes work due to some technical limitation.

3.1. That's fine. Generally moving the root folder is not necessary. And additionally, you can also set up multi-ScrapBook to manage the data in multiple folders.

3.2. The original "List View" feature in ScrapBook has been removed. Actually, the feature had been removed in ScrapBook since version 1.4. And although it exists in ScrapBook Plus, there are still some unfixed bugs.

The current "List View" feature is actually a different feature (to view all data items in plain). See [revision history](https://github.com/danny0838/firefox-scrapbook/wiki/History#scrapbook-x-1120a26) for detail.

**Comment by githmw** [comment]
Danny:

Thanks again for the information.

I must admit I did not read the revision history. If I had, I would
not have bothered you with the List View question.


Harry

**Comment by danny0838** [comment]
You're welcome. Would you mind if we erase your account and password information above?

**Comment by githmw** [comment]
Danny:

Yes, go ahead and erase that information. Excellent thought.


Harry
